### ISSUE TITLE
sigsegv/nil pointer running 'ocm toi bootstrap package actionOne' when no credentials required

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#352]
**What happened**:

I have a toiPackage that requires no credentials.   See describe output below 
```
ocm toi describe package 'directory::./ocm/component-archive//example.com/ocm/toi/helloworld:1.0.0' name=toi-package-two
Warning: repository is no OCI registry, consider importing it or use upload repository with option ' -X ociuploadrepo=...
TOI Package example.com/ocm/toi/helloworld:1.0.0[toi-package-two]
  Package Description:
    installPackageTwo

  Additional Resources:
    - configFile: downloadable user configuration file template)
    - credentialsFile: downloadable credential file template)
    - readme.txt
  Supported Actions:
    - actionOne: provided by "name"="toi-executor-one"
    - actionThree: provided by "name"="toi-executor-two"
    - actionTwo: provided by "name"="toi-executor-one"
    - actionfour: provided by "name"="toi-executor-two"
  no credentials required
```

However when I run 
```
ocm toi bootstrap package actionOne 'directory::./ocm/component-archive//example.com/ocm/toi/helloworld:1.0.0'
```
I get 
```
Warning: repository is no OCI registry, consider importing it or use upload repository with option ' -X ociuploadrepo=...'using executor config:
  toiExecutorTemplateLibraryOne:
    data: toiExecutorTemplateLibraryOneData
    fromLibraryTwo:
      data: toiExecutorTemplateLibraryTwoData
  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x289f0c2]

goroutine 1 [running]:
github.com/open-component-model/ocm/pkg/toi/install.GetCredentials({0x37d5828, 0xc00064cf00}, 0x0, 0x0, 0xc000a6e420)
	/home/runner/work/ocm/ocm/pkg/toi/install/credentials.go:116 +0xa82
github.com/open-component-model/ocm/pkg/toi/install.ExecuteAction({0x378d4e8, 0xc0008d8ab0}, {0x377d608, 0xc000223808}, {0x7fffa119022a, 0x9}, 0xc0009df200, 0x0, {0x0, 0x0, ...}, ...)
	/home/runner/work/ocm/ocm/pkg/toi/install/action.go:378 +0x96c
github.com/open-component-model/ocm/pkg/toi/install.Execute({0x378d4e8, 0xc0008d8ab0}, {0x377d608, 0xc000223808}, {0x7fffa119022a, 0x9}, 0x0, {0x0, 0x0}, {0x0, ...}, ...)
	/home/runner/work/ocm/ocm/pkg/toi/install/execute.go:47 +0x3e7
github.com/open-component-model/ocm/cmds/ocm/commands/toicmds/package/bootstrap.(*action).Out(0xc0003244e0)
	/home/runner/work/ocm/ocm/cmds/ocm/commands/toicmds/package/bootstrap/cmd.go:285 +0x3c9
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.HandleOutput({0x378dc20, 0xc0003244e0}, {0x378ed20, 0xc001209380}, {0xc0006a5e70?, 0x0?, 0x0?})
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/handling.go:99 +0x266
github.com/open-component-model/ocm/cmds/ocm/commands/toicmds/package/bootstrap.(*Command).Run(0xc00043b380)
	/home/runner/work/ocm/ocm/cmds/ocm/commands/toicmds/package/bootstrap/cmd.go:229 +0x351
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.SetupCommand.func1(0xc000cfe400?, {0xc0003244c0, 0x2, 0x2})
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/command.go:190 +0x130
github.com/spf13/cobra.(*Command).execute(0xc000e01208, {0xc000072220, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:943 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d14008)
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:1071 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x37d2820?)
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:995 +0x13
main.main()
	/home/runner/work/ocm/ocm/cmds/ocm/main.go:17 +0xdc
```

**What you expected to happen**:

I expect the install to just work as no credentials are required.    Or, if for some reason credentials really are required I expect a message telling me what I need to provide and how I should provide it.

In any case, I shouldn't be getting a SIGSEGV.

**How to reproduce it (as minimally and precisely as possible)**:

See description

**Anything else we need to know**:

Nope

**Environment**:

ocm version 0.11.0

**Comment by jakobmoellerdev** [comment]
Closing as obsolete. TOI (Transfer/Orchestration/Installation) is a v1-only system and is not being ported to OCM v2. These issues are superseded by the v2 constructor and transfer modules.
