### ISSUE TITLE
Bug: `make ..` fails with panic: runtime error: invalid memory address or nil pointer dereference [recovered] 	panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1033c8bc0]

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-project#63]
I cloned this repo to my local machine and tried to run it or just run tests via `make run` or `make test` but all of them are failing with error:
```
make test                
/Users/I540484/go/src/ocm-controller/bin/controller-gen rbac:roleName=ocm-controller-manager-role crd webhook paths="./api/..." paths="./controllers/..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1033c8bc0]

goroutine 16 [running]:
go/types.(*Checker).handleBailout(0x14001b6a800, 0x14000c0dd18)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/check.go:367 +0x9c
panic({0x103693a60?, 0x103c1ff30?})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x10375cc70, 0x103c287a0})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:228 +0x320
go/types.(*Config).sizeof(...)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x10375cc70?, 0x103c287a0?})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x103762e58, 0x103bf4940}, 0x14001b6a800, 0x103c287a0, 0x14000c2dda8)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).conversion.func1({0x10375cc98?, 0x14003dc08c0?}, 0x14000c2dda8)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/conversions.go:24 +0x74
go/types.(*Checker).conversion(0x14001b6a800, 0x14000c2dd80, {0x10375cc98, 0x14003dc08c0})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/conversions.go:44 +0x19c
go/types.(*Checker).callExpr(0x14001b6a800, 0x14000c2dd80, 0x14004970e80)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/call.go:224 +0xa60
go/types.(*Checker).exprInternal(0x14001b6a800, 0x0, 0x14000c2dd80, {0x1037612c0, 0x14004970e80}, {0x0, 0x0})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1374 +0xd0
go/types.(*Checker).rawExpr(0x14001b6a800, 0x0, 0x14000c2dd80, {0x1037612c0?, 0x14004970e80?}, {0x0?, 0x0?}, 0x0)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).exprInternal(0x14001b6a800, 0x0, 0x14000c2dd80, {0x103760ba0, 0x14004965ec0}, {0x0, 0x0})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1320 +0x150
go/types.(*Checker).rawExpr(0x14001b6a800, 0x0, 0x14000c2dd80, {0x103760ba0?, 0x14004965ec0?}, {0x0?, 0x0?}, 0x0)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).exprOrType(0x14001b6a800, 0x14000c2dd80, {0x103760ba0?, 0x14004965ec0?}, 0xe8?)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1573 +0x48
go/types.(*Checker).selector(0x14001b6a800, 0x14000c2dd80, 0x1400495ac90, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/call.go:769 +0x42c
go/types.(*Checker).exprInternal(0x14001b6a800, 0x0, 0x14000c2dd80, {0x10375f820, 0x1400495ac90}, {0x0, 0x0})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1325 +0xa60
go/types.(*Checker).rawExpr(0x14001b6a800, 0x0, 0x14000c2dd80, {0x10375f820?, 0x1400495ac90?}, {0x0?, 0x0?}, 0x0)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x14001b6a800, 0x0?, 0x14000c2dd80, {0x10375f820?, 0x1400495ac90?})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).varDecl(0x14001b6a800, 0x14005297200, {0x140050c4a40, 0x1, 0x1}, {0x0, 0x0}, {0x10375f820, 0x1400495ac90})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/decl.go:521 +0x140
go/types.(*Checker).objDecl(0x14001b6a800, {0x103767f78, 0x14005297200}, 0x0)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/decl.go:194 +0x7ec
go/types.(*Checker).packageObjects(0x14001b6a800)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x14001b6a800, {0x140045bbb40, 0x8, 0x8})
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0x1400037f9e0, 0x140045bf080)
	/Users/I540484/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.0/pkg/loader/loader.go:286 +0x2d8
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0x140045bf080)
	/Users/I540484/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.0/pkg/loader/loader.go:99 +0x44
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0x140044032f0, 0x140045bf080)
	/Users/I540484/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.0/pkg/loader/refs.go:268 +0x304
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x73?)
	/Users/I540484/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.0/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 71
	/Users/I540484/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.0/pkg/loader/refs.go:260 +0x230
make: *** [manifests] Error 2
``

***environment***:

```
go version
go version go1.22.0 darwin/arm64

ocm version
{"Major":"0", "Minor":"7", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.7.0", "GitCommit":"a2b9f7464074572632c40feb4db19c65b5cedd94", "GitTreeState":"", "BuildDate":"2024-02-23T17:20:54Z", "GoVersion":"go1.21.7", "Compiler":"gc", "Platform":"darwin/arm64"}

 sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ....
      User Name: sb (I5....)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: X Tage, 1 Stunde und 28 Minuten
```

**Comment by morri-son** [comment]
related to https://github.com/open-component-model/ocm-controller/pull/374
